defaults: &defaults
  working_directory: /work_space
  docker:
    - image: hashicorp/terraform:0.11.7

version: 2
jobs:
  plan:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: terraform plan
          command: |
            export AWS_ACCESS_KEY_ID=$AK
            export AWS_SECRET_ACCESS_KEY=$SK
            export AWS_DEFAULT_REGION="ap-northeast-1"

            cd terraform
            
            terraform init -upgrade
            terraform get
            terraform plan
  apply:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: terraform apply
          command: |
            export AWS_ACCESS_KEY_ID=$AK
            export AWS_SECRET_ACCESS_KEY=$SK
            export AWS_DEFAULT_REGION="ap-northeast-1"
            cd terraform
            
            terraform init -upgrade
            terraform get
            terraform apply -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - plan:
          filters: 
            branches:
              only: 
                - master
                - release/production
      - apply:
          filters: 
            branches:
              only: 
                - release/production
          requires:
            - plan 
